import { Poppins } from 'next/font/google'
import { Providers } from './providers'
import NavigationMenu from '@/components/NavigationMenu'
import Footer from '@/components/Footer'
import type { Metadata } from 'next'
import './globals.css'

const font = Poppins({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body className={font.className}>
        <NavigationMenu />
        <Providers>{children}</Providers>
        <Footer />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/base16/onedark.min.css"
          referrerPolicy="no-referrer"
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"
          referrerPolicy="no-referrer"
          defer
        />
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/javascript.min.js"
          integrity="sha512-H69VMoQ814lKjFuFwLImb4OwoK8Rm8fcvsqZexaxjp/VkJfEnrt5TO7oaOdNlMf/j51QUctfLTe8+rgozW7l2A=="
          referrerPolicy="no-referrer"
          defer
        />
      </body>
    </html>
  )
}
